import os
from supabase import create_client
from dotenv import load_dotenv
from datetime import date  # <-- ADDED: For handling the 'sta' date column

# Load environment variables from .env
load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")
TABLE_NAME = os.getenv("SUPABASE_TABLE", "users")

# --- ADDED: New table name ---
EMOTION_TABLE_NAME = os.getenv("SUPABASE_EMOTION_TABLE", "users_emotionVal")
# -----------------------------

# Create Supabase client
supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

# -------- DATABASE FUNCTIONS (Users) -------- #

def insert_user(name, emailid, password, age):
    data = {
        "Name": name,
        "Email_id": emailid,
        "Password": password,
        "Age": age
    }
    return supabase.table(TABLE_NAME).insert(data).execute().data


def fetch_user(user_id):
    result = (
        supabase.table(TABLE_NAME)
        .select("*")
        .eq("user_id", user_id)
        .execute()
    )
    return result.data

def login_email(email):
    res = (
        supabase.table(TABLE_NAME)
        .select("*")
        .eq("Email_id", email)
        .execute()
    )
    return res.data

# --- ADDED: New functions for users_emotionVal table ---

def insert_emotion_log(user_id, emotion_json, log_date=None):
    """
    Inserts a new emotion log for a specific user.
    The 'sta' column from your screenshot is assumed to be the date.
    """
    # If no date is provided, default to today's date
    if log_date is None:
        log_date = date.today().isoformat()

    data = {
        "user_id": user_id,
        "emotion_key": emotion_json,
        "sta": log_date  # 'sta' column from your screenshot
    }
    # Note: 'id' is auto-generated by Supabase, so we don't send it.
    return supabase.table(EMOTION_TABLE_NAME).insert(data).execute().data

def fetch_emotions_by_user(user_id):
    """
    Fetches all emotion logs for a specific user.
    """
    result = (
        supabase.table(EMOTION_TABLE_NAME)
        .select("*")
        .eq("user_id", user_id)
        .execute()
    )
    return result.data

def fetch_single_emotion_log(log_id):
    """
    Fetches a single emotion log by its primary key 'id'.
    """
    result = (
        supabase.table(EMOTION_TABLE_NAME)
        .select("*")
        .eq("id", log_id)  # 'id' is the primary key
        .execute()
    )
    return result.data

def delete_emotion_log(log_id):
    """
    Deletes a single emotion log by its primary key 'id'.
    """
    result = (
        supabase.table(EMOTION_TABLE_NAME)
        .delete()
        .eq("id", log_id)
        .execute()
    )
    return result.data

# --------------------------------------------------------